### PR TITLE
Calendar font size fix

### PR DESCRIPTION
**Pull request by micahmills**

### CODE REVIEW

**Comment by corsacca** [comment]
@micahmills 
This made it all bigger instead of back to normal size?

**Comment by micahmills** [comment]
Should be fixed now

**Comment by corsacca** [comment]
@micahmills,
This still feels big. What do you see?
image

**Comment by micahmills** [comment]
After a couple of tweaks here is what I see.
Screenshot 2024-01-11 at 4 14 05 PM
Screenshot 2024-01-11 at 4 24 21 PM

**Comment by corsacca** [comment]
Updates:

Bigger size and correct calc. Here 15% is now shown correctly

image
to:
image

**Comment by corsacca** [comment]
@micahmills 
This was the percentage before:
image

now:
image

what do you think of this last commit for the stroke width? https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/pull/248/commits/bec21aefe52316cc95c4dbe9fc3aad9bddb68310

How shall we set the circle size? We were passing in 80 for the radius.

**Comment by micahmills** [comment]
The circle size is set to the size of the container, where are you seeing the radius set to 80?

**Comment by micahmills** [comment]
I actually removed those in the last commit because they don't actually do anything anymore. The radius and stroke are set based off the size of the container.

**Comment by corsacca** [comment]
So is the best way to set the size of the circle to set `style="width:200px"` on the container?

**Comment by micahmills** [comment]
Yes that will do it. That being said, I would try not to set a fixed pixel width on a container because that is likely to break in various viewports.

**Pull request merged**
