### PR TITLE
Set a default locale for js dates

### PR DESCRIPTION
**Pull request by corsacca**

### CODE REVIEW

**Review by micahmills — COMMENTED** [review]
This is a much better solution and appears to work as expected. 

There are a few places in the calendar headers showing the month and year that we need to replace `.toFormat('MMMM y')` with `.toLocaleString({ month: 'short', year: 'numeric' })}`. I made the changes locally but don't have permission to push them to this branch. So I can create a separate PR for that.

**Comment by corsacca** [comment]
Awesome! Thanks @micahmills

**Comment by corsacca** [comment]
There are a couple places we're using `toFormat` as a key.
`"month": date_time.toFormat('y_MM'),` is the main one. That one will need to stay as it is.

**Comment by micahmills** [comment]
unless we are seeing things that aren't working in a particular locale we probably should leave them as they are.

**Pull request merged**
