### PR TITLE
Create and save prayer field posts with the correct permalink. Change…

### PR DESCRIPTION
**Pull request by corsacca**
… back to WP Admin Link

Correct links for these guys:
image

### CODE REVIEW

**Comment by squigglybob** [comment]
@corsacca clicking on View Prayer Fuel button takes me to the admin page http://test.disciple.domains/wp-admin/admin.php?page=dt_prayer_campaigns.  The url seems to be missing the lang param http://test.disciple.domains/prayer/fuel/second-test?lang= also I think it should be going to the day number not the slug so /prayer/fuel/2 I think this also affects the link in "this link" is now live.

It could be because that link is not showable yet as the campaign hasn't got to that day, but it does work if you switch the slug for the day number

The other links work great.

**Comment by corsacca** [comment]
@squigglybob My view prayer fuel link looks like `http://campaigns.local/fixed/prayer/fuel/6?lang=en_US`

**Comment by corsacca** [comment]
Did you do "Add New" or click on one of the flags?

**Comment by corsacca** [comment]
Creating Prayer Fuel with "Add New" button then shows wrong links

**Comment by corsacca** [comment]
Issue logged, so will merge in and then address issue.

**Pull request merged**
