### PR TITLE
Feat/update day in prayer fuel

### LINKED ISSUE #60: update days in scheduled posts if the campaign start date is changed

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #60

### CODE REVIEW

**Comment by squigglybob** [comment]
as long as I haven't got any phpcs errors to fix, this one is totally ready ( I hope 🤞🏻  ) for checking @corsacca 😃

**Comment by squigglybob** [comment]
Watch the 28th
image

image

The fixed post stays on the correct date

**Comment by squigglybob** [comment]
* all posts should be published as soon as they are imported or created.
* posts created for a particular date, should have their day and link meta changed to reflect the new day in the campaign that they now fall on ( when changing the campaign start date )
* in the code the list of posts at the bottom of /prayer/list and /prayer/fuel are now querying and sorting by the day meta tag instead of publish_date

**Comment by corsacca** [comment]
@squigglybob I created a post for Aug 15
image

Then i changed the start day of the campaign and the post date was deleted and the day changed.

**Comment by corsacca** [comment]
Actually it is not letting me set a specific day for the post. Or refresh it show the date has disappeared

**Comment by squigglybob** [comment]
I'm not sure I fully follow you, but for sure the way those 2 inputs interact could be made more intuitive

**Pull request merged**
