### PR TITLE
feat: email settings tab

### LINKED ISSUE #120: Add section for email strings on the admin side
a tab in the prayer campaigns called
email settings

stays there even when a porch is not selected

* select campaign
* create strings to go in
  * the signup email
  * the other email

Then we can get rid of the email settings translations tile on the campaigns record

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #120

### CODE REVIEW

**Comment by squigglybob** [comment]
@corsacca this one should be done, as long as the checks come out clean

**Comment by corsacca** [comment]
@squigglybob nice work.

 is the structure change intentional? it means the emails need to be updated to the new way of getting the strings.
image
Default should have a key.

**Comment by corsacca** [comment]
I merged in a branch i had started that removes the "campaign_description" field.

**Comment by corsacca** [comment]
We were previously able to add
`<a href="link">etxt</a>`
That is being stripped out now.

**Comment by squigglybob** [comment]
> @squigglybob nice work.
> 
> is the structure change intentional? it means the emails need to be updated to the new way of getting the strings. image Default should have a key.

@corsacca I hadn't picked up on the default thing being an = sign. I can put that in for sure.

I'll also add "a" to the allowed tags that won't get stripped out

**Comment by squigglybob** [comment]
@corsacca I accidentally did both things in the above commit.

So it should now save the default translations under ""

**Comment by squigglybob** [comment]
I can't see any travis thingy's here so can't see if it's ok, but I have done the code work to get it to use default translation in the emails now

**Pull request merged**
